### PR TITLE
Add title query filter to items

### PR DESCRIPTION
**Pull request by napzzz**

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Lovely. Let me take a look.

**Review by vanessa-cooper-1 — CHANGES_REQUESTED** [review]
Umm… something is not quite right, please take another look and try again.

**Review by vanessa-cooper — APPROVED** [review]
Looking good! Now we can move on to the UI. 
I'll send you more details on Snack.

**Review by vanessa-cooper-1 — CHANGES_REQUESTED** [review]
Umm… something is not quite right, please take another look and try again.

**Pull request closed without merging**
